version: "2.1"
services:
  schema-registry:
    image: jeqo/confluent-platform-schema-registry:3.1.1-2.11
    links:
      - kafka
      - zookeeper
  kafka:
    image: jeqo/confluent-platform-kafka:3.1.1-2.11
    links:
      - zookeeper
  zookeeper:
    image: jeqo/confluent-platform-zookeeper:3.1.1-2.11