version: '2'
services:
  schema-registry:
    image: jeqo/confluent-platform-schema-registry:3.2.1
    links:
      - kafka
      - zookeeper
  kafka:
    image: jeqo/confluent-platform-kafka:3.2.1
    links:
      - zookeeper
  zookeeper:
    image: jeqo/confluent-platform-zookeeper:3.2.1
