kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-0
  labels:
    type: local
    app: kafka-broker
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/kafka-0"
