kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-1
  labels:
    type: local
    app: kafka-zookeeper
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/kafka-zookeeper-1"
