/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.eneco.trading.kafka.connect.twitter;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Hashtag extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Hashtag\",\"namespace\":\"com.eneco.trading.kafka.connect.twitter\",\"fields\":[{\"name\":\"text\",\"type\":[\"null\",\"string\"]}],\"connect.name\":\"com.eneco.trading.kafka.connect.twitter.Hashtag\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence text;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Hashtag() {}

  /**
   * All-args constructor.
   */
  public Hashtag(java.lang.CharSequence text) {
    this.text = text;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return text;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: text = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /** Creates a new Hashtag RecordBuilder */
  public static com.eneco.trading.kafka.connect.twitter.Hashtag.Builder newBuilder() {
    return new com.eneco.trading.kafka.connect.twitter.Hashtag.Builder();
  }
  
  /** Creates a new Hashtag RecordBuilder by copying an existing Builder */
  public static com.eneco.trading.kafka.connect.twitter.Hashtag.Builder newBuilder(com.eneco.trading.kafka.connect.twitter.Hashtag.Builder other) {
    return new com.eneco.trading.kafka.connect.twitter.Hashtag.Builder(other);
  }
  
  /** Creates a new Hashtag RecordBuilder by copying an existing Hashtag instance */
  public static com.eneco.trading.kafka.connect.twitter.Hashtag.Builder newBuilder(com.eneco.trading.kafka.connect.twitter.Hashtag other) {
    return new com.eneco.trading.kafka.connect.twitter.Hashtag.Builder(other);
  }
  
  /**
   * RecordBuilder for Hashtag instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Hashtag>
    implements org.apache.avro.data.RecordBuilder<Hashtag> {

    private java.lang.CharSequence text;

    /** Creates a new Builder */
    private Builder() {
      super(com.eneco.trading.kafka.connect.twitter.Hashtag.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.eneco.trading.kafka.connect.twitter.Hashtag.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Hashtag instance */
    private Builder(com.eneco.trading.kafka.connect.twitter.Hashtag other) {
            super(com.eneco.trading.kafka.connect.twitter.Hashtag.SCHEMA$);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'text' field */
    public java.lang.CharSequence getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public com.eneco.trading.kafka.connect.twitter.Hashtag.Builder setText(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.text = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'text' field */
    public com.eneco.trading.kafka.connect.twitter.Hashtag.Builder clearText() {
      text = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Hashtag build() {
      try {
        Hashtag record = new Hashtag();
        record.text = fieldSetFlags()[0] ? this.text : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
