/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.eneco.trading.kafka.connect.twitter;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserMention extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserMention\",\"namespace\":\"com.eneco.trading.kafka.connect.twitter\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"screen_name\",\"type\":[\"null\",\"string\"]}],\"connect.name\":\"com.eneco.trading.kafka.connect.twitter.UserMention\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence screen_name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UserMention() {}

  /**
   * All-args constructor.
   */
  public UserMention(java.lang.Long id, java.lang.CharSequence name, java.lang.CharSequence screen_name) {
    this.id = id;
    this.name = name;
    this.screen_name = screen_name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return screen_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: screen_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'screen_name' field.
   */
  public java.lang.CharSequence getScreenName() {
    return screen_name;
  }

  /**
   * Sets the value of the 'screen_name' field.
   * @param value the value to set.
   */
  public void setScreenName(java.lang.CharSequence value) {
    this.screen_name = value;
  }

  /** Creates a new UserMention RecordBuilder */
  public static com.eneco.trading.kafka.connect.twitter.UserMention.Builder newBuilder() {
    return new com.eneco.trading.kafka.connect.twitter.UserMention.Builder();
  }
  
  /** Creates a new UserMention RecordBuilder by copying an existing Builder */
  public static com.eneco.trading.kafka.connect.twitter.UserMention.Builder newBuilder(com.eneco.trading.kafka.connect.twitter.UserMention.Builder other) {
    return new com.eneco.trading.kafka.connect.twitter.UserMention.Builder(other);
  }
  
  /** Creates a new UserMention RecordBuilder by copying an existing UserMention instance */
  public static com.eneco.trading.kafka.connect.twitter.UserMention.Builder newBuilder(com.eneco.trading.kafka.connect.twitter.UserMention other) {
    return new com.eneco.trading.kafka.connect.twitter.UserMention.Builder(other);
  }
  
  /**
   * RecordBuilder for UserMention instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserMention>
    implements org.apache.avro.data.RecordBuilder<UserMention> {

    private long id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence screen_name;

    /** Creates a new Builder */
    private Builder() {
      super(com.eneco.trading.kafka.connect.twitter.UserMention.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.eneco.trading.kafka.connect.twitter.UserMention.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.screen_name)) {
        this.screen_name = data().deepCopy(fields()[2].schema(), other.screen_name);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UserMention instance */
    private Builder(com.eneco.trading.kafka.connect.twitter.UserMention other) {
            super(com.eneco.trading.kafka.connect.twitter.UserMention.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.screen_name)) {
        this.screen_name = data().deepCopy(fields()[2].schema(), other.screen_name);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.eneco.trading.kafka.connect.twitter.UserMention.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.eneco.trading.kafka.connect.twitter.UserMention.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.eneco.trading.kafka.connect.twitter.UserMention.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public com.eneco.trading.kafka.connect.twitter.UserMention.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'screen_name' field */
    public java.lang.CharSequence getScreenName() {
      return screen_name;
    }
    
    /** Sets the value of the 'screen_name' field */
    public com.eneco.trading.kafka.connect.twitter.UserMention.Builder setScreenName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.screen_name = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'screen_name' field has been set */
    public boolean hasScreenName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'screen_name' field */
    public com.eneco.trading.kafka.connect.twitter.UserMention.Builder clearScreenName() {
      screen_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public UserMention build() {
      try {
        UserMention record = new UserMention();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.screen_name = fieldSetFlags()[2] ? this.screen_name : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
