FROM openjdk:8-jdk

ENV KAFKA_BOOTSTRAP_SERVERS "kafka:9092"
ENV PUSH_GATEWAY_SERVER "pushgateway:9091"

ADD target/kafka-producers-ack-one-jar-with-dependencies.jar .

CMD java -jar kafka-producers-ack-one-jar-with-dependencies.jar