version: '2'
services:
  file_connector:
    build: .
    volumes:
      - ./ouput:/tmp/output
    networks:
      - default
      - confluentplatform_default
networks:
  confluentplatform_default:
    external: true
