# This exercise is trying to fill 2 segments (20KB) that + additional metadata will compact 2 segments and we will end up
# with a few more than 1 or 2 records available by compaction.
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-compaction
spec:
  template:
    metadata:
      name: kafka-producer-compaction
    spec:
      containers:
      - name: kafka-producer-compaction
        image: jeqo/kafka-producer:1.0.0
        env:
        - name: METRIC_NAME
          value: kafka_producer_compaction
        - name: TOPIC
          value: compacted
        - name: WAIT_SEG
          value: "5"
        - name: MAX_MESSAGES
          value: "20"
        - name: KEY_MAX
          value: "0"
        - name: MESSAGE_SIZE
          value: "1000"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
       - name: config-volume
         configMap:
           name: kafka-producer-config
      restartPolicy: Never
