---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "jeqo/apache-kafka:0.10.1.1-2.11"
          ports:
            - name: kafka
              containerPort: 9092
          volumeMounts:
            - name: "kafka-cluster-config"
              mountPath: "/config"
          command: ["/bin/sh","-c"]
          args: ["/docker-entrypoint.sh && bin/kafka-server-start.sh /config/server.properties"]
      volumes:
          - name: kafka-cluster-config
            configMap:
              name: kafka-cluster-config
